server:
  port: 8181

spring:
  application:
    name: trade-signal
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/opentrades
  flyway:
    url: jdbc:postgresql://localhost:5432/opentrades
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
binance:
  binance-uri: https://api.binance.com
  profit: 1.02
  stop: 0.98
  symbols:
    - MANAUSDT
    - BATUSDT
    - CHZUSDT
    - COMPUSDT
    - SANDUSDT
    - ADAUSDT
    - XLMUSDT
    - AUDIOUSDT
    - ZRXUSDT
    - XRPUSDT
    - AVAXUSDT
    - LINKUSDT
    - LTCUSDT
    - AAVEUSDT
    - SLPUSDT
    - DOTUSDT
    - MKRUSDT
    - AXSUSDT
    - FETUSDT
    - BCHUSDT
    - GRTUSDT
    - SKLUSDT
    - FTMUSDT
    - HBARUSDT
    - MATICUSDT
    - SOLUSDT
    - BTCUSDT
kraken:
  api-uri: https://api.kraken.com
  api-key:
  api-secret:
  profit: 1.05
  stop: 0.96
  mac-algorithm: HmacSHA512
  symbols:
    - MANAUSDT
    - BATUSD
    - CHZUSD
    - COMPUSD
    - SANDUSD
    - ADAUSD
    - ADAUSDT
    - XXLMZUSD
    - AUDIOUSD
    - ZRXUSD
    - XRPUSDT
    - AVAXUSDT
    - LINKUSDT
    - LINKUSD
    - XLTCZUSD
    - AAVEUSD
    - DOTUSDT
    - DOTUSD
    - MKRUSD
    - AXSUSD
    - FETUSD
    - BCHUSDT
    - BCHUSD
    - GRTUSD
    - FTMUSD
    - MATICUSDT
    - MATICUSD
    - SOLUSDT
    - SOLUSD