spring:
  application:
    name: trade-signal
  sql:
    init:
      mode: always
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/opentrades
    driverClassName: org.postgresql.Driver
project:
  binance-uri: https://api.binance.com
  profit: 1.02
  stop: 0.98
  symbols:
    - BTCUSDT
    - SOLUSDT
    - MATICUSDT
    - HBARUSDT
    - FTMUSDT
    - SKLUSDT
    - DOTUSDT
    - GRTUSDT
    - BCHUSDT
    - FETUSDT
    - AXSUSDT
    - MKRUSDT
    - SLPUSDT
    - AAVEUSDT
    - LTCUSDT
    - LINKUSDT
    - AVAXUSDT
    - XRPUSDT
    - ZRXUSDT
    - AUDIOUSDT
    - XLMUSDT
    - ADAUSDT
    - SANDUSDT
    - COMPUSDT
    - CHZUSDT
    - BATUSDT
    - MANAUSDT
kraken:
  api-uri: https://api.kraken.com
  api-key: apikey
  api-secret: apisecret
  profit: 1.05
  stop: 0.96
